title: "Ramon Alexander Sosich"
description: "Ethical Dissonance Theory (EDT) | Psychology, Ethics, Scientific Behaviour"
theme: jekyll-theme-minimal
markdown: kramdown

nav:
  - Home: index.md
  - Ethical Dissonance Theory: edt.md
  - CV: cv.md
  - Publications: publications.md
  
include:
  - _includes/head-custom.html
